server:
  port: 8083

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackuri: forward:/user-service-fallback
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: department-service
                fallbackuri: forward:/department-service-fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream